import { readFile, writeFile } from 'node:fs/promises';
const data = JSON.parse(await readFile(new URL('../data/chats.json', import.meta.url), 'utf8'));
if (!Number.isInteger(data.revision) || !Array.isArray(data.groups)) throw new Error('Invalid timeline data');
await writeFile(new URL('../dist/published-chats.js', import.meta.url), `// Generated by npm run build from the public timeline.\nexport default ${JSON.stringify(data, null, 2)};\n`);
console.log(`Built public timeline snapshot: ${data.groups.length} updates.`);
const settings = JSON.parse(await readFile(new URL('../data/settings.json', import.meta.url), 'utf8'));
await writeFile(new URL('../dist/published-settings.js', import.meta.url), `// Public profile settings only.\nexport default ${JSON.stringify(settings, null, 2)};\n`);
